#!/usr/bin/env bash
# This script tells a story based on the contents of /etc/passwd

# Read /etc/passwd line by line
while IFS=: read -r username _ user_id _ _ home_directory shell; do
    # Display the formatted story
    echo "The user $username is part of the $user_id gang, lives in $home_directory and rides $shell. $user_id's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
