#!/usr/bin/env bash
# This script displays all active IPv4 addresses on the server machine.

# Here we use the ip command to list active IP addresses
ip -4 -o addr show | awk '{print $4}' | cut -d/ -f1

