#!/usr/bin/env bash
# This script displays all active IPv4 addresses on the machine.

# Use ifconfig to display active IP addresses, filtering and formatting the output with grep and awk
ifconfig | grep 'inet ' | awk '{print $2}'

