#!/usr/bin/env bash
# This script generates an RSA key pair with the private key named 'school',
# a key size of 4096 bits, and the passphrase 'betty'.

ssh-keygen -t rsa -b 4096 -f school -N "betty"
